
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-edit","number":77,"title":"Create Edit for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/77"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-create","number":76,"title":"Create Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/76"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-index","number":75,"title":"Index Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/75"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rytuose-MenuItemReview-create","number":74,"title":"Added create page and index page for menuitem review","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/74"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rytuose-MenuItemReview-placeholder","number":73,"title":"Added placeholders for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/73"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rytuose-MenuItemReview-tableComponent","number":72,"title":"Added menu item review table and tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/72"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-pages","number":71,"title":"Copy Placeholders for UCSBDiningCommonsMenuItem pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/71"}]
