
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"josephli","number":68,"title":"move files from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/68"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-table","number":67,"title":"Table Component for UCSBDiningCommonsMenuItem plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/67"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rytuose-MenuItemReview-formComponent","number":66,"title":"Added menu item review form component","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/66"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-form","number":65,"title":"Form Component for UCSBDiningCommonsMenuItem plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/65"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-fixture","number":64,"title":"Create fixtures for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/64"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-crud","number":63,"title":"Copy files for Backend CRUD API UCSBDiningCommonsMenuItem from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/63"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rytuose-MenuItemReview-fixtures","number":62,"title":"Added menu item review fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/62"}]
