
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"wzqd-Articles-create","number":85,"title":"Add Create page for articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/85"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"wzqd-Articles-placeholder","number":84,"title":"Create placeholder for articles and add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-3/pull/84"}]
